### ISSUE TITLE
Interactive_cloth_segmentation_CV/U-2-Net/saved_models/u2net/u2net.pth

### ISSUE THREAD

**Issue by designnner** [SudeepRed/Interactive-Cloth-Segmentation-with-Saliency-Guided-Style-Transfer#1]
I need you .pth file,please.

**Comment by designnner** [comment]
If you can see it, please reply as soon as possible

**Comment by SudeepRed** [comment]
Hey, thanks for testing my framework!
I forgot to share this google [drive folder](https://drive.google.com/drive/folders/1AfClJnV-_OZhaqI9K2ijUJnDo0lVt1pW?usp=sharing)

**Comment by SudeepRed** [comment]
I will update the readme as well

**Comment by designnner** [comment]
thank you buddy
